language: node_js
node_js: 
- "0.12.7"
install:
- "npm install"
- "npm install bower -g"
- "bower install"
- "gem install scss_lint -v 0.49.0"
#configure Travis to load Firefox before running gulp test
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
script:
- "gulp build"
env: CI=true